# Generated by Django 4.0 on 2023-02-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
