# Generated by Django 4.0 on 2023-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0005_alter_blog_description_alter_blog_poston'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'FAQ',
            },
        ),
    ]
