# Generated by Django 4.0 on 2023-03-22 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0008_treatments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('treatmentid', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specialist', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Doctor/')),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 3, 21)),
        ),
    ]
