# Generated by Django 4.0 on 2023-03-23 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0009_doctor_alter_blog_poston'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('treatmentid', models.IntegerField()),
                ('Dob', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('Appoinmenttime', models.IntegerField()),
                ('Appoinmentdate', models.IntegerField()),
                ('doctorid', models.IntegerField()),
                ('feedback', models.TextField()),
            ],
            options={
                'db_table': 'Appoinment',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 3, 22)),
        ),
    ]
