# Generated by Django 4.1.7 on 2023-04-18 12:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0011_alter_appoinment_appoinmentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatments',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
