# Generated by Django 4.1.7 on 2023-05-02 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0013_alter_appoinment_doctorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='Gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='poston',
            field=models.DateField(default=datetime.date(2023, 5, 2)),
        ),
    ]
