# Generated by Django 4.1.7 on 2023-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0014_appoinment_gender_alter_blog_poston'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Gender',
            field=models.CharField(max_length=20),
        ),
    ]
