# Generated by Django 4.1.7 on 2023-05-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkarmapp', '0016_alter_blog_poston_patientreports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreports',
            old_name='report_date',
            new_name='Report_date',
        ),
        migrations.AlterField(
            model_name='patientreports',
            name='DoctorFeedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patientreports',
            name='PatientFeedback',
            field=models.TextField(default=''),
        ),
    ]
